name: Downloader

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "URLs (uma por linha)"
        required: true
      audio_format:
        description: "Formato de áudio (ex: wav, mp3)"
        required: false
        default: "wav"
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Gera config.json a partir dos inputs
      - name: Create config.json
        env:
          URLS: ${{ inputs.urls }}
          AUDIO_FORMAT: ${{ inputs.audio_format }}
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const urls = (process.env.URLS || '')
            .split(/\r?\n/)
            .map(s => s.trim())
            .filter(Boolean);

          const dir = process.env.DOWNLOAD_DIR || 'downloads';
          const fmt = process.env.AUDIO_FORMAT || 'wav';

          const cfg = {
            download_directory: dir,
            audio_format: fmt,
            urls
          };

          fs.writeFileSync('config.json', JSON.stringify(cfg, null, 2));
          console.log('config.json:\n', JSON.stringify(cfg, null, 2));
          NODE

      - name: Run downloader (node index.js)
        run: node index.js

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: downloads-${{ github.run_id }}
          path: ${{ inputs.download_dir }}
          if-no-files-found: error

